In [ ]:
#desenvolvido por Tatiana Regina

In [ ]:
# Bibliotecas
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import datetime as dt
import numpy as np
import kagglehub

# Download latest version
path = kagglehub.dataset_download("olistbr/brazilian-ecommerce")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'brazilian-ecommerce' dataset.
Path to dataset files: /kaggle/input/brazilian-ecommerce

In [ ]:
# Carrega os arquivos csv em dataframes pandas:
customers = pd.read_csv(path+"/olist_customers_dataset.csv")
geolocation = pd.read_csv(path+"/olist_geolocation_dataset.csv")
order_items = pd.read_csv(path+"/olist_order_items_dataset.csv")
payments = pd.read_csv(path+"/olist_order_payments_dataset.csv")
reviews = pd.read_csv(path+"/olist_order_reviews_dataset.csv")
orders = pd.read_csv(path+"/olist_orders_dataset.csv")
products = pd.read_csv(path+"/olist_products_dataset.csv")
product_category = pd.read_csv(path+"/product_category_name_translation.csv")

In [ ]:
#Importar tabela de-para entre estados e Região
df_estados_regiao = pd.read_csv("/tb_de_para_estados.csv")
display(df_estados_regiao)

   Sigla               Estado        Região
0     AC                 Acre         Norte
1     AP                Amapá         Norte
2     AM             Amazonas         Norte
3     PA                 Pará         Norte
4     RO             Rondônia         Norte
5     RR              Roraima         Norte
6     TO            Tocantins         Norte
7     AL              Alagoas      Nordeste
8     BA                Bahia      Nordeste
9     CE                Ceará      Nordeste
10    MA             Maranhão      Nordeste
11    PB              Paraíba      Nordeste
12    PE           Pernambuco      Nordeste
13    PI                Piauí      Nordeste
14    RN  Rio Grande do Norte      Nordeste
15    SE              Sergipe      Nordeste
16    DF     Distrito Federal  Centro-Oeste
17    GO                Goiás  Centro-Oeste
18    MT          Mato Grosso  Centro-Oeste
19    MS   Mato Grosso do Sul  Centro-Oeste
20    ES       Espírito Santo       Sudeste
21    MG         Minas Gerais       Sudeste
22    RJ       Rio de Janeiro       Sudeste
23    SP            São Paulo       Sudeste
24    PR               Paraná           Sul
25    RS    Rio Grande do Sul           Sul
26    SC       Santa Catarina           Sul

In [ ]:
#Agrupando dados de Pedido, Pagamento, Estado de Entrega, Categoria de Produto
#e Avaliações para analise
order_payments = orders.merge(payments, on='order_id')
order_customer = order_payments.merge(customers, on='customer_id')
order_products = order_customer.merge(order_items, on='order_id')
order_all = order_products.merge(products, on='product_id')
order_all = order_all.merge(reviews, on='order_id')


# Convert date columns to datetime objects in the pandas DataFrame
order_all['order_purchase_timestamp'] = pd.to_datetime(order_all['order_purchase_timestamp'])
order_all['order_approved_at'] = pd.to_datetime(order_all['order_approved_at'])
order_all['order_delivered_carrier_date'] = pd.to_datetime(order_all['order_delivered_carrier_date'])
order_all['order_delivered_customer_date'] = pd.to_datetime(order_all['order_delivered_customer_date'])
order_all['order_estimated_delivery_date'] = pd.to_datetime(order_all['order_estimated_delivery_date'])

# Create 'order_date' column by unifying purchase and approved timestamps
# Use order_purchase_timestamp if available, otherwise order_approved_at
order_all['order_date'] = order_all['order_purchase_timestamp'].fillna(order_all['order_approved_at'])

# Criação tempo estimado de entrega: campo dif_deliv_estimat
order_all['dif_deliv_estimat'] = order_all['order_delivered_customer_date'] - order_all['order_estimated_delivery_date']
order_all['dif_deliv_compra'] = order_all['order_delivered_customer_date'] - order_all['order_date']

# Create 'dif_deliv_estimat_days' and 'dif_deliv_compra_days' for Spark compatibility
order_all['dif_deliv_estimat_days'] = order_all['dif_deliv_estimat'].dt.days
order_all['dif_deliv_compra_days'] = order_all['dif_deliv_compra'].dt.days

In [ ]:
##Trazendo de-para de Estados e Regiões para analise
order_all=order_all.left(df_estados_regiao, on=order_all['customer_state']=df_estados_regiao['Sigla'])

In [ ]:
##Validação e avaliação das colunas a serem utilizadas na analise
display(order_all.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 117329 entries, 0 to 117328
Data columns (total 42 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       117329 non-null  object
 1   customer_id                    117329 non-null  object
 2   order_status                   117329 non-null  object
 3   order_purchase_timestamp       117329 non-null  datetime64[ns]
 4   order_approved_at              117314 non-null  datetime64[ns]
 5   order_delivered_carrier_date   116094 non-null  datetime64[ns]
 6   order_delivered_customer_date  114858 non-null  datetime64[ns]
 7   order_estimated_delivery_date  117329 non-null  datetime64[ns]
 8   payment_sequential             117329 non-null  int64
 9   payment_type                   117329 non-null  object
 10  payment_installments           117329 non-null  int64
 11  payment_value                  117329 non-null  float64
 12  customer_unique_id             117329 non-null  object
 13  customer_zip_code_prefix       117329 non-null  int64
 14  customer_city                  117329 non-null  object
 15  customer_state                 117329 non-null  object
 16  order_item_id                  117329 non-null  int64
 17  product_id                     117329 non-null  object
 18  seller_id                      117329 non-null  object
 19  shipping_limit_date            117329 non-null  object
 20  price                          117329 non-null  float64
 21  freight_value                  117329 non-null  float64
 22  product_category_name          115634 non-null  object
 23  product_name_lenght            115634 non-null  float64
 24  product_description_lenght     115634 non-null  float64
 25  product_photos_qty             115634 non-null  float64
 26  product_weight_g               117309 non-null  float64
 27  product_length_cm              117309 non-null  float64
 28  product_height_cm              117309 non-null  float64
 29  product_width_cm               117309 non-null  float64
 30  review_id                      117329 non-null  object
 31  review_score                   117329 non-null  int64
 32  review_comment_title           13892 non-null   object
 33  review_comment_message         49679 non-null   object
 34  review_creation_date           117329 non-null  object
 35  review_answer_timestamp        117329 non-null  object
 36  order_date                     117329 non-null  datetime64[ns]
 37  dif_deliv_estimat              114858 non-null  timedelta64[ns]
 38  dif_deliv_compra               114858 non-null  timedelta64[ns]
 39  dif_deliv_estimat_days         114858 non-null  float64
 40  dif_deliv_compra_days          114858 non-null  float64
 41  regiao                         117329 non-null  object
dtypes: datetime64[ns](6), float64(12), int64(5), object(17), timedelta64[ns](2)
memory usage: 37.6+ MB

None

In [ ]:
##Avaliando os dados na menor granularidade para selecionar apenas as colunas a serem utilizadas na analise dos dados:
display(order_all).where(order_all['order_id']=	'00018f77f2f0320c557190d7a144bdd3')

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,payment_sequential,payment_type,...,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp,order_date,dif_deliv_estimat,dif_deliv_compra,dif_deliv_estimat_days,dif_deliv_compra_days,regiao
84679,00018f77f2f0320c557190d7a144bdd3,f6dd3ec061db4e3987629fe6b26e5cce,delivered,2017-04-26 10:53:06,2017-04-26 11:05:13,2017-05-04 14:35:00,2017-05-12 16:04:24,2017-05-15,1,credit_card,...,NaN,NaN,2017-05-13 00:00:00,2017-05-15 11:34:13,2017-04-26 10:53:06,-3 days +16:04:24,16 days 05:11:18,-3.0,16.0,Sudeste

In [ ]:
##Reduzindo a tabela, apenas com as colunas que serão utilizadas.
df_order_all = order_all[['order_id','order_status','order_item_id','order_approved_at','order_purchase_timestamp','order_date','order_delivered_carrier_date','order_delivered_customer_date','order_estimated_delivery_date','customer_unique_id','regiao','customer_state','customer_city','payment_type','payment_value','price','freight_value','product_category_name','review_score','dif_deliv_estimat_days','dif_deliv_compra_days']]
display(df_order_all.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 117329 entries, 0 to 117328
Data columns (total 21 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       117329 non-null  object
 1   order_status                   117329 non-null  object
 2   order_item_id                  117329 non-null  int64
 3   order_approved_at              117314 non-null  datetime64[ns]
 4   order_purchase_timestamp       117329 non-null  datetime64[ns]
 5   order_date                     117329 non-null  datetime64[ns]
 6   order_delivered_carrier_date   116094 non-null  datetime64[ns]
 7   order_delivered_customer_date  114858 non-null  datetime64[ns]
 8   order_estimated_delivery_date  117329 non-null  datetime64[ns]
 9   customer_unique_id             117329 non-null  object
 10  regiao                         117329 non-null  object
 11  customer_state                 117329 non-null  object
 12  customer_city                  117329 non-null  object
 13  payment_type                   117329 non-null  object
 14  payment_value                  117329 non-null  float64
 15  price                          117329 non-null  float64
 16  freight_value                  117329 non-null  float64
 17  product_category_name          115634 non-null  object
 18  review_score                   117329 non-null  int64
 19  dif_deliv_estimat_days         114858 non-null  float64
 20  dif_deliv_compra_days          114858 non-null  float64
dtypes: datetime64[ns](6), float64(5), int64(2), object(8)
memory usage: 18.8+ MB

None

In [ ]:
#Remoção de registros duplicados df_order_all
original_rows = df_order_all.shape[0]
df_order_all.drop_duplicates(inplace=True)

print(f"Número original de linhas: {original_rows}")
print(f"Número de linhas após remover duplicatas: {df_order_all.shape[0]}")

Número original de linhas: 117329
Número de linhas após remover duplicatas: 116226

/tmp/ipykernel_11047/1768321591.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_order_all.drop_duplicates(inplace=True)

In [ ]:
#Avaliando todos os status do pedido presentes na base
display(df_order_all['order_status'].unique())

array(['delivered', 'invoiced', 'shipped', 'processing', 'canceled',
       'unavailable', 'approved'], dtype=object)

In [ ]:
#Lead time por regiao entre compra, aprovação, postagem e entrega
df_order_all['lead_time_compra_aprovacao'] = (df_order_all['order_purchase_timestamp']-df_order_all['order_approved_at'] ).dt.days
df_order_all['lead_time_aprovacao_postagem'] = (df_order_all['order_delivered_carrier_date']-df_order_all['order_approved_at'] ).dt.days
df_order_all['lead_time_postagem_entrega'] = (df_order_all['order_delivered_customer_date']-df_order_all['order_delivered_carrier_date'] ).dt.days

#Aplicação de filtro no Data Frame para que a base de analise tenha apenas pedidos entregues
df_order_all_deliv=df_order_all.where(df_order_all['order_status']=='delivered')
df_order_all_deliv=df_order_all.where(df_order_all['order_item_id']==1)
df_order_all_deliv=df_order_all_deliv.dropna()
df_order_all_deliv['anomes'] = df_order_all_deliv['order_purchase_timestamp'].dt.to_period('M')
df_order_all_deliv = df_order_all_deliv[(df_order_all_deliv['anomes'] >= pd.Period('2017-01', freq='M')) & (df_order_all_deliv['anomes'] <= pd.Period('2018-08', freq='M'))]
df_order_all_deliv.info()

/tmp/ipykernel_11047/580193947.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_order_all['lead_time_compra_aprovacao'] = (df_order_all['order_purchase_timestamp']-df_order_all['order_approved_at'] ).dt.days
/tmp/ipykernel_11047/580193947.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_order_all['lead_time_aprovacao_postagem'] = (df_order_all['order_delivered_carrier_date']-df_order_all['order_approved_at'] ).dt.days
/tmp/ipykernel_11047/580193947.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_order_all['lead_time_postagem_entrega'] = (df_order_all['order_delivered_customer_date']-df_order_all['order_delivered_carrier_date'] ).dt.days

<class 'pandas.core.frame.DataFrame'>
Index: 98002 entries, 0 to 117328
Data columns (total 25 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       98002 non-null  object
 1   order_status                   98002 non-null  object
 2   order_item_id                  98002 non-null  float64
 3   order_approved_at              98002 non-null  datetime64[ns]
 4   order_purchase_timestamp       98002 non-null  datetime64[ns]
 5   order_date                     98002 non-null  datetime64[ns]
 6   order_delivered_carrier_date   98002 non-null  datetime64[ns]
 7   order_delivered_customer_date  98002 non-null  datetime64[ns]
 8   order_estimated_delivery_date  98002 non-null  datetime64[ns]
 9   customer_unique_id             98002 non-null  object
 10  regiao                         98002 non-null  object
 11  customer_state                 98002 non-null  object
 12  customer_city                  98002 non-null  object
 13  payment_type                   98002 non-null  object
 14  payment_value                  98002 non-null  float64
 15  price                          98002 non-null  float64
 16  freight_value                  98002 non-null  float64
 17  product_category_name          98002 non-null  object
 18  review_score                   98002 non-null  float64
 19  dif_deliv_estimat_days         98002 non-null  float64
 20  dif_deliv_compra_days          98002 non-null  float64
 21  lead_time_compra_aprovacao     98002 non-null  float64
 22  lead_time_aprovacao_postagem   98002 non-null  float64
 23  lead_time_postagem_entrega     98002 non-null  float64
 24  anomes                         98002 non-null  period[M]
dtypes: datetime64[ns](6), float64(10), object(8), period[M](1)
memory usage: 19.4+ MB

In [ ]:
df_order_all_deliv.to_csv('/df_order_all_deliv3.csv', index=False)
print('DataFrame df_order_all_deliv exported to df_order_all_deliv.csv')

DataFrame df_order_all_deliv exported to df_order_all_deliv.csv

 Lead time entre compra, aprovação, postagem e entrega. • Correlação entre atrasos e review_score

### Correlação entre Atrasos e Review Score

Satisfação do Cliente • Distribuição de review_score e temas recorrentes (se text mining). • Drivers de satisfação: tempo de entrega, preço, categoria.  • Identificação de riscos de churn.

Oportunidades e Recomendação • Otimização de frete em rotas críticas. • Estratégias de pricing/cross-sell por categoria/região. • Priorizar sellers com alto NPS e baixo tempo de entrega.

Necessário cálcular o NPS